# Web Drivers
minium:
  webdriver:
    desiredCapabilities:
      browserName: chrome
    window:
      maximized: true

# Configuration that can be injected in your tests
  config:
    searches:
      Minium Github:
        - https://github.com/viltgroup/minium
      Selenium:
        - https://www.selenium.dev/
